[package]
name = "aloh-engine"
version = "0.0.0"
description = "Capture friction't"
authors = ["Exr0n <mail@exr0n.com>"]
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
